### ISSUE TITLE
set up  Kanban board

### ISSUE THREAD

**Issue by bernabasy** [bernabasy/API-based-webapp#21]
https://github.com/bernabasy/API-based-webapp/projects/1

In my team, we are two people: @tobuya and @bernabasy

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Good implementations ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far! In this project, you need to work as a `team`, which means that you should not assign all the cards in your kanban plan to `individuals`, but assign some of them as a group. Please assign some cards as a `team` 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/211397735-1ec6acff-eb7f-4a29-8b3b-6f59a03318f9.png)
 

## Optional suggestions
- [ ] [OPTIONAL]  It would be great if you could write more information about the team members and your Kanban plan in the issue description 😃 

![image](https://user-images.githubusercontent.com/63915024/211398060-3bc5dd89-09a2-4c50-8d77-01e7f01923b7.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by leonardodiasb** [comment]
# Status: ✔️ Project Approved ✔️ 

Hi @bernabasy,

Everything is looking great! Please, start the project. :shipit:
Congratulations! 🎉

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
